### ISSUE TITLE
Accept other ways of populating the worker's namespace

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-queueserver#114] opened 2020-12-18 01:03 UTC
We currently use IPython profile startup scripts for most beamline configurations. IPython startup scripts are executed in a single namespace, sorted alphanumerically. To make that sorting explicit, we have adopted the _convention_ of prefixing them with a number, like `00-startup.py`.

This system is mostly a result of inertia, borne of copy/pasting the first working bluesky configuration (CSX) around the ring during NSLS-II's rapid scale-up. There are many downsides to our system. Two important ones are:

* Python scripts that begin with a digit are not importable as modules. This makes it difficult to build tests and documentation around them.
* Executing multiple scripts in one namespace may be convenient at small scales, but it confuses linters and modern editors (as they cannot see where variables are defined). This has led to serious bugs in practice. In one memorable incident at SRX, the critical `databroker.Broker` instance that was saving user data, `db`, was shadowed in a subsequent script and was therefore garbage collected and unsubscribed from the `RunEngine`.

The MVP of the worker was tuned to the reality that we use IPython profiles mostly named `profile_collection` and they tend to include scripts named like `[0-9][0-9]*.py`. (The worker skips any scripts that do not adhere to this convention even though IPython does not.)

https://github.com/bluesky/bluesky-queueserver/blob/994b858b0acadeb601aa94e5ec0c15fadc2ea93b/bluesky_queueserver/manager/profile_ops.py#L208-L210

This was a reasonable MVP. But I think we should pivot to work with other approaches and generally try to steer _away_ from IPython profiles in the future, given the downsides outlined above.

I suggest changing `start_re_worker` in the following ways:

- Provide a [mutually exclusive group of parameters](https://docs.python.org/3/library/argparse.html#mutual-exclusion) including:
    - a mode that accepts an importable module as in `-m my_pacakge.my_module`
    - a mode that accepts a script as in `--script path/to/script.py`
    - a mode that accepts an IPython profile as in `--profile PROFILE_NAME`
- The name `profile_collection` is just a convention (one with at least one exception within NSLS-II and possibly more elsewhere). I suggest changing `--profile-collection` to just `--profile PROFILE_NAME`, taking a profile name, and respecting [`IPYTHON_DIR`](https://ipython.readthedocs.io/en/stable/development/config.html) to find the directory on the filesystem.

**Comment by dmgav** [comment] 2020-12-18 03:25
I think it's a good idea to support other ways to populate the namespace, such as by importing a module or running a script. As for suggested modifications to how 'profile-collection' is loaded, I can not totally agree, because the proposed changes artificially limit functionality. I can see cases when such limitations would be inconvenient (especially for organizing unit tests). Also even if we choose to eradicate IPython workflow completely, we will have to fully support it for a long time, since many users may want to run the experiments both from IPython and using RE Manager and will not want to maintain two separate sets of profiles. I don't see a problem implementing an option to specify profile name with `--profile PROFILE_NAME` option to load a specific IPython profile using `IPYTHON_DIR`, but I think that we should keep an option to specify path using `--profile_collection PATH_TO_PROFILE_COLLECTION` so that RE Manager could load a profile collection located in any accessible directory. This gives total of 4 mutually exclusive options.

**Comment by dmgav** [comment] 2020-12-18 13:02
I think `--profile_collection` could be renamed into `--startup-path` or something like this. Also I think that the other options should be named as `--startup-module`, `--startup-script` and `--startup-profile`.

**Comment by dmgav** [comment] 2020-12-18 13:12
`(The worker skips any scripts that do not adhere to this convention even though IPython does not.)`
Do you think that this implementation is incorrect? This part of code was discussed many times and there were no objections. Also probably it should be kept this way to avoid loading junk.

**Comment by danielballan** [comment] 2020-12-18 16:56
I like your suggestion of four mutually exclusive arguments, and I like the names you have proposed for them. You make a good point that supporting a `--startup-path` (perhaps `--startup-directory`?) option is more flexible than requiring that the directory be part of an IPython profile in `IPYTHON_DIR` and may be particular useful in the context of testing.

> Do you think that this implementation is incorrect? There is no problem to change it so that it loads alphabetically ordered list of .py files.

I think it's a useful convention to use digit prefixes on files to make the execution order really clear, but I don't think we should skip files that fail to adhere to the convention. The implementation of the Manager here should match IPython exactly because it would be surprising if `ipython` / `bsui` executed a script and our RE worker skipped over it. That would be hard to debug if someone wasn't familiar with this detail.

> This part of code was discussed many times and there were no objections. 

No worries! It's possible that the reviewers were not familiar with the behavior of IPython because the convention of digit prefixes is so widespread. I don't recall if I looked at it myself at the time, but this detail would be easy to miss.

**Comment by mrakitin** [comment] 2020-12-18 17:59
> > This part of code was discussed many times and there were no objections.
> 
> No worries! It's possible that the reviewers were not familiar with the behavior of IPython because the convention of digit prefixes is so widespread. I don't recall if I looked at it myself at the time, but this detail would be easy to miss.

I knew about IPython's approach to load non-digit-prefixed files (basically, all `*.py` files), and helped to make it clear to some beamline scientists in the past. I guess it was overlooked during my (and others') reviews in previous PRs. I think it should be fixed rather earlier than later.

I like the idea of other options to supply ophyd objects. One comment about the implementation here. The structure of the profile directory should be:
```
profile_collection
|_startup
  |_<our .py files>
|_<other-files-and-dirs>
```
however in our case we are skipping the `startup` directory. I think it should be "normalized".

Also, FYI: this is how to access the corresponding `startup` dir in IPython:
https://github.com/NSLS-II-XFP/profile_collection/blob/4b23e8952e824e91a6cbb816a758e728841f58e0/startup/00-base.py#L31

**Comment by dmgav** [comment] 2020-12-18 18:15
Actually the code in question was discussed quite intensively before it was included in the PR. But this is not an issue. It's a minor change. It's good that it is noticed before the system is deployed. The structure of `profile_collection` directory doesn't seem to matter if we rename the parameter to `--startup-dir`, as it is assumed that we are pointing to the directory that contains startup files. I guess for the `--startup-profile` option we should use correct profile collection directory structure. 

As for other sources, we are planning to integrate `happi` in the system. Once we start working on it, there will be extra parameter(s) with `happi` address and port number. And I guess the right sequence will be to load devices from the database and then load the profile collection. Ideally the profile collection should define only plans, but it could define some devices that are not (yet) in the database.

**Comment by dmgav** [comment] 2021-01-04 18:41
The issue is partially addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/119: 
- Implemented loading of startup files based on IPython profile name (`--startup-profile`). 
- Changed `--profile-collection` to `--startup-dir`. 
- Removed restrictions on startup file names: all `*.py` files are loaded in the worker namespace in alphabetical order of their names.

**Comment by dmgav** [comment] 2021-01-07 19:28
Potential approaches to loading startup data by executing a single or importing a module are discussed in https://gist.github.com/dmgav/187cecb46f47e4cc7df57098e879c9d2 and https://gist.github.com/danielballan/d581e2c6fb73da2669294e839eb1ed44. While importing an installed module using `importlib.import_module()` function is straightforward, loading a script proved problematic, since there exists no standard and reliable way to ensure unique referencing for local imports from the script. One of the discussed solution is to restrict the options and implement only the option of importing the startup data from a module.

**Comment by danielballan** [comment] 2021-01-07 19:43
Lifting a comment from my DMs with @dmgav:

I think we need to support:

1. A package on the import path (preferred long term approach)
2. IPython profile startup (legacy approach)
3. MAYBE a single stand-alone script (useful to testing, tutorials, and lightweight demos) but it can only import things that are on the import path; we won't add its directory to `sys.path` at runtime.

I would be happy with just (1) and (2), adding (3) if we have a reason to need it. I think that messing with `sys.path` at runtime is not something we should do until we have a specific user and use case for it.

**Comment by dmgav** [comment] 2021-01-07 20:56
`3. MAYBE a single stand-alone script (useful to testing, tutorials, and lightweight demos) but it can only import things that are on the import path; we won't add its directory to `sys.path` at runtime.`

My against partial implementation of script loading is that local imports are typical in Python scripts. I think that we either have to try to implement it fully or restrict users to importing installed modules. Potential user case: https://github.com/NSLS-II-BMM/profile_collection.git is based on local imports. The potential solution for loading scripts with local imports: https://gist.github.com/danielballan/d581e2c6fb73da2669294e839eb1ed44#gistcomment-3585979

**Comment by dmgav** [comment] 2021-03-15 20:39
The issue is resolved in PRs https://github.com/bluesky/bluesky-queueserver/pull/119 and https://github.com/bluesky/bluesky-queueserver/pull/120

**Closed by dmgav** 2021-03-15 20:39 UTC
