### ISSUE TITLE
move server to FastAPI

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#26] opened 2020-09-02 04:31 UTC
The current API server is implemented via aiohttp, but we are using FastAPI for several other projects and there is no reason to maintain a different tech-stack here.

**Comment by dmgav** [comment] 2020-11-30 17:49
The issue is addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/44

**Closed by dmgav** 2020-11-30 17:49 UTC
Labels: server
